#!/usr/bin/bash
~/.config/hypr/scripts/tools/island.py &
while true; do
  # echo ""
  out=$(cat ~/.config/hypr/files/store_to_waybar/dynamic_out.txt)
  echo "$out"
  # cat ~/.config/hypr/scripts/tools/dynamic_out.txt
  sleep 0.5
done
