hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE QT_QPA_PLATFORMTHEME QT_QPA_PLATFORM QT_WAYLAND_DISABLE_WINDOWDECORATION QT_IM_MODULE GTK_IM_MODULE XMODIFIERS")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE QT_QPA_PLATFORMTHEME QT_QPA_PLATFORM QT_WAYLAND_DISABLE_WINDOWDECORATION QT_IM_MODULE GTK_IM_MODULE XMODIFIERS")
  hl.exec_cmd("fcitx5 -d --replace")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
  hl.exec_cmd("ambxst")
  hl.exec_cmd("sh -c 'sleep 1; nm-applet --indicator'")
  hl.exec_cmd("sh -c 'sleep 1; rfkill unblock bluetooth; bluetoothctl power on'")
  hl.exec_cmd("sh -c 'sleep 2; blueman-applet'")
  hl.exec_cmd("sh -c 'sleep 3; /usr/bin/cc-switch'")
  hl.exec_cmd("sh -c 'sleep 3; ~/.config/hypr/scripts/register-extra-binds.sh'")
end)
